"""Owner-reported rendering fixes (2026-07-27 screenshot feedback).

1. 今日详情 is flat (no collapsible) and absorbs the current-condition rows.
2. Air quality stays collapsible but SAYS it can be expanded.
3. Life-index tips render two per row.
4. AI reports/briefs become rich BLOCKS — rich html= collapses newlines.
5. Draft streaming previews are plain text (thinking blocks show raw <b>).
6. A "小雨" sky ships the rain chart even when the next hour is dry.
"""

import os
import unittest
from datetime import datetime, timedelta, timezone

os.environ.setdefault("BOT_TOKEN", "test-token")
os.environ.setdefault("QWEATHER_API_KEY", "test-qweather-key")

from core.config import settings
from core.handlers.report import plain_stream_preview
from core.handlers.weather import should_attach_rain_chart
from domain.models import AirQuality, DailyForecast, LifeIndex, WeatherData
from utils.rich_formatter import (
    _index_pairs_table,
    build_realtime_blocks,
    build_report_blocks,
)

TZ = timezone(timedelta(hours=8))


def make_weather(**kwargs) -> WeatherData:
    now = datetime.now(TZ)
    base = dict(
        location_name="顺德, 广东省",
        coords="113.3,22.8",
        now_temp=25,
        now_text="小雨",
        now_icon="305",
        now_humidity=92,
        now_vis=19,
        summary="s",
        update_time=now,
        daily=[
            DailyForecast(
                date=datetime(now.year, now.month, now.day),
                temp_min=25,
                temp_max=33,
                text_day="小雨",
                icon_day="305",
                text_night="阴",
                icon_night="104",
                sunrise="05:59",
                sunset="19:08",
            )
        ],
        indices=[
            LifeIndex(type="3", name="穿衣指数", category="热", text=""),
            LifeIndex(type="8", name="舒适度指数", category="不舒适", text=""),
            LifeIndex(type="2", name="洗车指数", category="不宜", text=""),
            LifeIndex(type="5", name="紫外线指数", category="中等", text=""),
            LifeIndex(type="9", name="感冒指数", category="少发", text=""),
        ],
        air_quality=AirQuality(aqi=23, category="优", pm2p5=16),
    )
    base.update(kwargs)
    return WeatherData(**base)


def blocks_of_type(blocks, kind):
    return [b for b in blocks if b.get("type") == kind]


class RealtimeLayoutTests(unittest.TestCase):
    def test_today_details_is_flat_not_collapsible(self):
        blocks = build_realtime_blocks(make_weather())
        details_blocks = blocks_of_type(blocks, "details")
        # Air quality is the ONLY collapsible left on the realtime card.
        self.assertEqual(len(details_blocks), 1)
        self.assertIn("空气质量", str(details_blocks[0].get("summary")))

    def test_current_stats_merged_into_today_details_table(self):
        blocks = build_realtime_blocks(make_weather())
        tables = blocks_of_type(blocks, "table")
        merged = str(tables[0])
        # Current conditions (湿度) and today's forecast (日出) share one table.
        self.assertIn("湿度", merged)
        self.assertIn("日出", merged)

    def test_air_quality_summary_hints_expansion(self):
        blocks = build_realtime_blocks(make_weather())
        summary = str(blocks_of_type(blocks, "details")[0].get("summary"))
        self.assertIn("点击展开详情", summary)

    def test_index_tips_render_two_per_row(self):
        blocks = build_realtime_blocks(make_weather())
        tables = blocks_of_type(blocks, "table")
        tips_table = str(tables[-1])
        self.assertIn("穿衣指数", tips_table)
        # 5 tips → 3 rows of 2 columns, not 5 single-line bullets.
        rows = tables[-1]["cells"]
        self.assertEqual(len(rows), 3)

    def test_pairs_table_pads_odd_counts(self):
        rows = _index_pairs_table(["a", "b", "c"])["cells"]
        self.assertEqual(len(rows), 2)

    def test_header_line_carries_date_and_weekday(self):
        blocks = build_realtime_blocks(make_weather())
        heading_text = str(blocks[0])
        now = datetime.now(TZ)
        self.assertIn(now.strftime("%m-%d"), heading_text)
        self.assertIn("周", heading_text)

    def test_hero_line_is_labeled_realtime(self):
        blocks = build_realtime_blocks(make_weather())
        self.assertIn("实时", str(blocks[1]))


class ReportBlocksTests(unittest.TestCase):
    REPORT = (
        "🕐 数据时间：07月27日 01:04\n\n"
        "🌤️ <b>现在</b>\n小雨，25°C，体感26°C&amp;湿度92%。\n\n"
        "👕 <b>建议</b>\n• 带伞。\n\n"
        "🤖 Generated by gpt-5.6-terra"
    )

    def test_no_raw_html_tags_anywhere(self):
        blocks = build_report_blocks(self.REPORT, title="🤖 顺德 天气日报")
        self.assertNotIn("<b>", str(blocks))
        self.assertNotIn("</b>", str(blocks))

    def test_structure_title_paragraphs_footer(self):
        blocks = build_report_blocks(self.REPORT, title="🤖 顺德 天气日报")
        self.assertEqual(blocks[0]["type"], "heading")
        self.assertEqual(blocks[-1]["type"], "footer")
        self.assertIn("gpt-5.6-terra", str(blocks[-1]))
        # Each non-empty line is its own paragraph — structure survives.
        paragraphs = blocks_of_type(blocks, "paragraph")
        self.assertGreaterEqual(len(paragraphs), 5)

    def test_bold_becomes_an_entity_and_entities_unescape(self):
        blocks = build_report_blocks("🌤️ <b>现在</b>\nA&amp;B")
        flat = str(blocks)
        self.assertIn("'type': 'bold'", flat)
        self.assertIn("A&B", flat)

    def test_italic_entity(self):
        blocks = build_report_blocks("<i>细则</i>")
        self.assertIn("'type': 'italic'", str(blocks))


class StreamPreviewTests(unittest.TestCase):
    def test_tags_are_stripped_for_thinking_blocks(self):
        self.assertEqual(
            plain_stream_preview("🌤️ <b>现在</b>\n小雨，<i>25°C</i>"),
            "🌤️ 现在\n小雨，25°C",
        )

    def test_plain_text_passes_through(self):
        self.assertEqual(plain_stream_preview("没有标签 3 < 5 的普通文本"), "没有标签 3 < 5 的普通文本")


class RainChartTriggerTests(unittest.TestCase):
    def setUp(self):
        self._plots = settings.enable_weather_plots
        settings.enable_weather_plots = True

    def tearDown(self):
        settings.enable_weather_plots = self._plots

    def test_rainy_text_triggers_chart_even_with_dry_minutely(self):
        data = make_weather(now_text="小雨", is_raining=False)
        self.assertTrue(should_attach_rain_chart(data, "default"))

    def test_measured_rain_triggers_chart(self):
        data = make_weather(now_text="阴", is_raining=True)
        self.assertTrue(should_attach_rain_chart(data, "default"))

    def test_clear_sky_does_not(self):
        data = make_weather(now_text="晴", is_raining=False)
        self.assertFalse(should_attach_rain_chart(data, "default"))

    def test_rain_view_always_ships_the_chart(self):
        data = make_weather(now_text="晴", is_raining=False)
        self.assertTrue(should_attach_rain_chart(data, "rain"))

    def test_disabled_plots_win(self):
        settings.enable_weather_plots = False
        data = make_weather(now_text="小雨", is_raining=True)
        self.assertFalse(should_attach_rain_chart(data, "rain"))


if __name__ == "__main__":
    unittest.main()
