import os
import unittest
from datetime import datetime, timedelta, timezone
from types import SimpleNamespace
from unittest.mock import AsyncMock, patch

os.environ.setdefault("BOT_TOKEN", "test-token")
os.environ.setdefault("QWEATHER_API_KEY", "test-qweather-key")

from core.config import settings
from domain.models import WeatherData
from services.llm import LLMService, OpenAIProvider
from utils.cache import cache


def make_weather(coords: str = "116.40,39.90") -> WeatherData:
    tz = timezone(timedelta(hours=8))
    return WeatherData(
        source="qweather",
        location_name="北京, 北京市",
        coords=coords,
        now_temp=30,
        now_text="晴",
        now_icon="100",
        summary="晴",
        update_time=datetime(2026, 7, 26, 8, tzinfo=tz),
    )


class FakeStreamingProvider:
    def __init__(self, chunks):
        self.chunks = chunks
        self.model = "fake-model"
        self.stream_calls = 0

    async def generate_report(self, system_prompt: str, user_prompt: str) -> str:
        return "".join(self.chunks)

    async def generate_report_stream(self, system_prompt: str, user_prompt: str):
        self.stream_calls += 1
        for chunk in self.chunks:
            yield chunk

    async def aclose(self):
        pass


class StreamingReportTests(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.service = LLMService.__new__(LLMService)
        self.service.provider = FakeStreamingProvider(["<b>晴", "天</b>", "，适合出门"])
        self._old_ttl = settings.llm_report_cache_ttl_seconds
        self._old_streaming = settings.llm_streaming
        settings.llm_report_cache_ttl_seconds = 0
        settings.llm_streaming = True

    def tearDown(self):
        settings.llm_report_cache_ttl_seconds = self._old_ttl
        settings.llm_streaming = self._old_streaming

    async def test_stream_chunks_are_accumulated_and_reported(self):
        seen = []

        async def on_progress(partial: str):
            seen.append(partial)

        text = await self.service.generate_weather_report(make_weather(), on_progress=on_progress)

        self.assertIn("<b>晴天</b>，适合出门", text)
        self.assertIn("Generated by fake-model", text)
        self.assertEqual(seen[-1], "<b>晴天</b>，适合出门")
        self.assertEqual(len(seen), 3)

    async def test_model_time_header_is_replaced_with_live_data_time(self):
        # 模型硬写的时间行必须被剥掉，换成基于本次天气数据的新鲜时间行，
        # 否则缓存命中时用户会看到几小时前的"当前时间"。
        self.service.provider = FakeStreamingProvider(
            ["当前时间：07月26日 04:30\n\n🌤️ <b>现在</b>\n晴。"]
        )
        text = await self.service.generate_weather_report(make_weather())
        self.assertNotIn("04:30", text)
        self.assertTrue(text.startswith("🕐 数据时间：07月26日 08:00"))
        self.assertIn("<b>现在</b>", text)

    async def test_progress_callback_errors_do_not_break_generation(self):
        async def broken(_partial: str):
            raise RuntimeError("edit failed")

        text = await self.service.generate_weather_report(make_weather(), on_progress=broken)
        self.assertIn("<b>晴天</b>", text)


class ReportCacheTests(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.service = LLMService.__new__(LLMService)
        self.provider = FakeStreamingProvider(["缓存测试正文"])
        self.service.provider = self.provider
        self._old_ttl = settings.llm_report_cache_ttl_seconds
        self._old_streaming = settings.llm_streaming
        settings.llm_report_cache_ttl_seconds = 3600
        settings.llm_streaming = True

    def tearDown(self):
        settings.llm_report_cache_ttl_seconds = self._old_ttl
        settings.llm_streaming = self._old_streaming

    async def asyncTearDown(self):
        await cache.delete(self.service._report_cache_key(make_weather("116.41,39.91")))

    async def test_second_call_hits_cache_without_streaming(self):
        weather = make_weather("116.41,39.91")

        first = await self.service.generate_weather_report(weather)
        second = await self.service.generate_weather_report(weather)

        self.assertEqual(first, second)
        self.assertEqual(self.provider.stream_calls, 1)

    async def test_alert_changes_bust_the_cache_key(self):
        from domain.models import WarningAlert

        weather = make_weather("116.41,39.91")
        key_calm = self.service._report_cache_key(weather)

        weather.alerts = [
            WarningAlert(
                title="暴雨橙色预警",
                type="rain",
                level="橙色",
                text="预警",
                pub_time=datetime(2026, 7, 26, 8),
                source="QWeather",
            )
        ]
        key_alert = self.service._report_cache_key(weather)
        self.assertNotEqual(key_calm, key_alert)


class OpenAIStreamParsingTests(unittest.IsolatedAsyncioTestCase):
    async def test_responses_stream_yields_deltas(self):
        provider = OpenAIProvider(api_key="test-key")

        async def fake_stream():
            yield SimpleNamespace(type="response.output_text.delta", delta="早上")
            yield SimpleNamespace(type="response.output_text.delta", delta="好")
            yield SimpleNamespace(type="response.completed", response=None)

        create = AsyncMock(return_value=fake_stream())
        chunks = []
        try:
            with patch.object(provider.client.responses, "create", create):
                async for delta in provider.generate_report_stream("系统", "数据"):
                    chunks.append(delta)
        finally:
            await provider.aclose()

        self.assertEqual(chunks, ["早上", "好"])
        self.assertTrue(create.await_args.kwargs["stream"])

    async def test_responses_stream_falls_back_to_final_response_text(self):
        provider = OpenAIProvider(api_key="test-key")

        async def fake_stream():
            yield SimpleNamespace(
                type="response.completed",
                response=SimpleNamespace(output_text="整段返回"),
            )

        create = AsyncMock(return_value=fake_stream())
        chunks = []
        try:
            with patch.object(provider.client.responses, "create", create):
                async for delta in provider.generate_report_stream("系统", "数据"):
                    chunks.append(delta)
        finally:
            await provider.aclose()

        self.assertEqual(chunks, ["整段返回"])


if __name__ == "__main__":
    unittest.main()
